/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.Automobile;
import bean.Energie;
import bean.Tarif;
import bean.Usage;
import bean.Zone;
import javax.swing.JOptionPane;
import static main.Assurances.getController;

/**
 *
 * @author ATH
 */
public class AutomobileDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClasseDialog
     *
     * @param parent
     * @param modal
     */
    public AutomobileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        id_tarif = 0;
        initCB();
    }

    public AutomobileDialog(java.awt.Frame parent, boolean modal, Automobile automobile) {
        super(parent, modal);
        this.automobile = automobile;
        initComponents();
        id_tarif = this.automobile.getId_tarif();
        initCB();
        try {
            Tarif tarif = getController().getTarifController().getTarif(id_tarif);
            combo_classe.setSelectedItem(getController().getClasseController().getClasse(tarif.getId_classe()).getId());
            combo_groupe.setSelectedItem(getController().getGroupeController().getGroupe(tarif.getId_groupe()).getId());
            combo_zone.setSelectedItem(getController().getZoneController().getZone(tarif.getId_zone()).getZone());
            combo_zone.setSelectedItem(getController().getZoneController().getZone(tarif.getId_zone()).getZone());
            combo_usage.setSelectedItem(getController().getUsageController().getUsage(tarif.getId_usage()).getUsage());
            if (getController().getTarifController().getVehiculeController().getVehicule(tarif.getId()) != null) {
                radio_btn_vehicule.setSelected(true);
                combo_puissance.setSelectedItem(getController().getVehiculeMoteurController().getVehiculeMoteur(getController().getTarifController().getVehiculeController().getVehicule(tarif.getId()).getId_puissance()).getPuissance());
            } else {
                radio_btn_moto.setSelected(true);
                combo_puissance.setSelectedItem(getController().getMotoMoteurController().getMotoMoteur(getController().getTarifController().getMotoController().getMoto(tarif.getId()).getId_puissance()).getPuissance());
            }
            textField_tarif.setText("" + tarif.getTarif());
            textField_charge_utile.setText("" + this.automobile.getCharge_utile());
            textField_marque.setText(this.automobile.getMarque());
            textField_nombre_place.setText("" + this.automobile.getNombre_place());
            textField_numero_chassis.setText(this.automobile.getNumero_chassis());
            textField_numero_plaque.setText(this.automobile.getNumero_plaque());
            textField_type_auto.setText(this.automobile.getType());
            date_mise_circulation.setDate(this.automobile.getDate_circulation());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        btn_cancel = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo_classe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_groupe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combo_zone = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_usage = new javax.swing.JComboBox<>();
        radio_btn_vehicule = new javax.swing.JRadioButton();
        radio_btn_moto = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        combo_energie = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combo_puissance = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        textField_tarif = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textField_numero_plaque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textField_type_auto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textField_marque = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textField_numero_chassis = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textField_nombre_place = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        date_mise_circulation = new com.toedter.calendar.JDateChooser();
        textField_charge_utile = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Automobile");
        setModal(true);
        setResizable(false);

        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tarif Automobile"));

        jLabel2.setText("Classe");

        combo_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_classeActionPerformed(evt);
            }
        });

        jLabel3.setText("Groupe");

        combo_groupe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_groupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_groupeActionPerformed(evt);
            }
        });

        jLabel4.setText("Zone");

        combo_zone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_zone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_zoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Usage");

        combo_usage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_usage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_usageActionPerformed(evt);
            }
        });

        buttonGroup.add(radio_btn_vehicule);
        radio_btn_vehicule.setSelected(true);
        radio_btn_vehicule.setText("Véhicule");
        radio_btn_vehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_vehiculeActionPerformed(evt);
            }
        });

        buttonGroup.add(radio_btn_moto);
        radio_btn_moto.setText("Moto");
        radio_btn_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_motoActionPerformed(evt);
            }
        });

        jLabel6.setText("Energie");

        combo_energie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_energie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_energieActionPerformed(evt);
            }
        });

        jLabel7.setText("Puissance");

        combo_puissance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_puissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_puissanceActionPerformed(evt);
            }
        });

        jLabel1.setText("Prime annuel");

        textField_tarif.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(combo_classe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(combo_groupe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radio_btn_vehicule)
                                .addGap(18, 18, 18)
                                .addComponent(radio_btn_moto)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(combo_puissance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textField_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(450, 450, 450)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(combo_usage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_energie, 0, 100, Short.MAX_VALUE)
                            .addComponent(combo_zone, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(combo_groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(combo_zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_usage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_energie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_btn_vehicule)
                        .addComponent(radio_btn_moto))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_puissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Numéro de plaque");

        jLabel9.setText("Type auto");

        jLabel10.setText("Marque");

        jLabel11.setText("Numéro chassis");

        jLabel12.setText("Nombre de place");

        jLabel13.setText("Date de 1ère mise en circulation");

        jLabel14.setText("Charge utile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ok)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textField_nombre_place, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(textField_type_auto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                                .addComponent(textField_numero_plaque, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_numero_chassis)
                                            .addComponent(textField_marque)
                                            .addComponent(textField_charge_utile)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(date_mise_circulation, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField_numero_plaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(textField_numero_chassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(textField_type_auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(textField_nombre_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField_charge_utile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(date_mise_circulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_ok))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        ajouter_automobile();
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void radio_btn_vehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_vehiculeActionPerformed
        initCBPuissance();
        combo_energie.setEnabled(radio_btn_vehicule.isSelected());
        prime_annuel();
    }//GEN-LAST:event_radio_btn_vehiculeActionPerformed

    private void radio_btn_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_motoActionPerformed
        initCBPuissance();
        combo_energie.setEnabled(radio_btn_vehicule.isSelected());
        prime_annuel();
    }//GEN-LAST:event_radio_btn_motoActionPerformed

    private void combo_energieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_energieActionPerformed
        initCBPuissance();
        prime_annuel();
    }//GEN-LAST:event_combo_energieActionPerformed

    private void combo_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_classeActionPerformed
        prime_annuel();
    }//GEN-LAST:event_combo_classeActionPerformed

    private void combo_groupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_groupeActionPerformed
        prime_annuel();
    }//GEN-LAST:event_combo_groupeActionPerformed

    private void combo_zoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_zoneActionPerformed
        prime_annuel();
    }//GEN-LAST:event_combo_zoneActionPerformed

    private void combo_usageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_usageActionPerformed
        prime_annuel();
    }//GEN-LAST:event_combo_usageActionPerformed

    private void combo_puissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_puissanceActionPerformed
        prime_annuel();
    }//GEN-LAST:event_combo_puissanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AutomobileDialog dialog = new AutomobileDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    private Automobile automobile;
    private long id_tarif;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_ok;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> combo_classe;
    private javax.swing.JComboBox<String> combo_energie;
    private javax.swing.JComboBox<String> combo_groupe;
    private javax.swing.JComboBox<String> combo_puissance;
    private javax.swing.JComboBox<String> combo_usage;
    private javax.swing.JComboBox<String> combo_zone;
    private com.toedter.calendar.JDateChooser date_mise_circulation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio_btn_moto;
    private javax.swing.JRadioButton radio_btn_vehicule;
    private javax.swing.JTextField textField_charge_utile;
    private javax.swing.JTextField textField_marque;
    private javax.swing.JTextField textField_nombre_place;
    private javax.swing.JTextField textField_numero_chassis;
    private javax.swing.JTextField textField_numero_plaque;
    private javax.swing.JTextField textField_tarif;
    private javax.swing.JTextField textField_type_auto;
    // End of variables declaration//GEN-END:variables
    private void ajouter_automobile() {
        if (id_tarif == 0 || textField_numero_plaque.getText().isBlank()) {
            warning_information();
            return;
        }
        int nombre_place;
        try {
            nombre_place = Integer.parseInt(textField_nombre_place.getText());
        } catch (NumberFormatException e) {
            erreur_information();
            return;
        }
        double charge;
        try {
            charge = Double.parseDouble(textField_charge_utile.getText());
        } catch (NumberFormatException e) {
            erreur_information();
            return;
        }
        java.sql.Date date = new java.sql.Date(date_mise_circulation.getDate().getTime());
        if (automobile == null) {
            if (getController().getAutomobileController().getAutomobile(textField_numero_plaque.getText()) != null) {
                erreur_information();
                return;
            }
            getController().getAutomobileController().addAutomobile(
                    id_tarif,
                    nombre_place,
                    date,
                    textField_type_auto.getText(),
                    textField_numero_plaque.getText(),
                    textField_marque.getText(),
                    textField_numero_chassis.getText(),
                    charge
            );
        } else {
            getController().getAutomobileController().updateAutomobile(
                    automobile.getId(),
                    id_tarif,
                    nombre_place,
                    date,
                    textField_type_auto.getText(),
                    textField_numero_plaque.getText(),
                    textField_marque.getText(),
                    textField_numero_chassis.getText(),
                    charge
            );
        }
        success_information();
        dispose();
    }

    private void prime_annuel() {
        if (combo_classe.getSelectedIndex() < 0 || combo_energie.getSelectedIndex() < 0 || combo_groupe.getSelectedIndex() < 0 || combo_puissance.getSelectedIndex() < 0 || combo_usage.getSelectedIndex() < 0 || combo_zone.getSelectedIndex() < 0) {
            return;
        }

        long id_classe;
        try {
            id_classe = getController().getClasseController().getClasse(Long.parseLong(combo_classe.getSelectedItem().toString())).getId();
        } catch (NumberFormatException e) {
            return;
        }

        long id_groupe;
        try {
            id_groupe = getController().getGroupeController().getGroupe(Long.parseLong(combo_groupe.getSelectedItem().toString())).getId();
        } catch (NumberFormatException e) {
            return;
        }

        long id_zone;
        Zone zone = getController().getZoneController().getZone(combo_zone.getSelectedItem().toString());
        if (zone == null) {
            return;
        }
        id_zone = zone.getId();
        long id_usage;
        Usage usage = getController().getUsageController().getUsage(combo_usage.getSelectedItem().toString());
        if (usage == null) {
            return;
        }
        id_usage = usage.getId();

        if (radio_btn_vehicule.isSelected()) {
            long id_energie;
            Energie energie = getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString());
            if (energie == null) {
                return;
            }
            id_energie = energie.getId();
            long id_puissance_vehicule = getController().getVehiculeMoteurController().getVehiculeMoteur(combo_puissance.getSelectedItem().toString()).getId();
            Tarif tarif = getController().getTarifController().getTarif(id_classe, id_groupe, id_zone, id_usage, id_puissance_vehicule, id_energie);
            if (tarif != null) {
                id_tarif = tarif.getId();
                textField_tarif.setText("" + tarif.getTarif());
            } else {
                id_tarif = 0;
                textField_tarif.setText("");
            }

        } else {
            long id_puissance_moto = getController().getMotoMoteurController().getMotoMoteur(combo_puissance.getSelectedItem().toString()).getId();
            Tarif tarif = getController().getTarifController().getTarif(id_classe, id_groupe, id_zone, id_usage, id_puissance_moto);
            if (tarif != null) {
                id_tarif = tarif.getId();
                textField_tarif.setText("" + tarif.getTarif());
            } else {
                id_tarif = 0;
                textField_tarif.setText("");
            }
        }
    }

    private void success_information() {
        JOptionPane.showMessageDialog(this, "Opération effectuée avec success ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
    }

    private void warning_information() {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs ", "Champ vide ou manquant !", JOptionPane.WARNING_MESSAGE);
    }

    private void erreur_information() {
        JOptionPane.showMessageDialog(this, "Veuillez mettre de nouvelles données ", "Champ existant ou erroné !", JOptionPane.ERROR_MESSAGE);
    }

    private void initCBUsage() {
        combo_usage.removeAllItems();
        getController().getUsageController().getUsages().forEach((u) -> {
            combo_usage.addItem(u.getUsage());
        });
    }

    private void initCBClasse() {
        combo_classe.removeAllItems();
        getController().getClasseController().getClasses().forEach((c) -> {
            combo_classe.addItem("" + c.getId());
        });
    }

    private void initCBGroupe() {
        combo_groupe.removeAllItems();
        getController().getGroupeController().getGroupes().forEach((g) -> {
            combo_groupe.addItem("" + g.getId());
        });
    }

    private void initCBZone() {
        combo_zone.removeAllItems();
        getController().getZoneController().getZones().forEach((z) -> {
            combo_zone.addItem(z.getZone());
        });
    }

    private void initCBEnergie() {
        combo_energie.removeAllItems();
        getController().getEnergieController().getEnergies().forEach((e) -> {
            combo_energie.addItem(e.getEnergie());
        });
    }

    private void initCBPuissance() {
        combo_puissance.removeAllItems();
        if (radio_btn_vehicule.isSelected()) {
            long id_energie = 0;
            if (combo_energie.getSelectedIndex() > -1) {
                if (getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString()) != null) {
                    id_energie = getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString()).getId();
                }
            }

            getController().getVehiculeMoteurController().getVehiculeMoteurs(id_energie).forEach((p) -> {
                combo_puissance.addItem(p.getPuissance());
            });
        }
        if (radio_btn_moto.isSelected()) {
            getController().getMotoMoteurController().getMotoMoteurs().forEach((p) -> {
                combo_puissance.addItem(p.getPuissance());
            });
        }
    }

    private void initCB() {
        initCBUsage();
        initCBClasse();
        initCBGroupe();
        initCBZone();
        initCBEnergie();
        initCBPuissance();
    }
}
