/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import bean.Classe;
import bean.Compagnie;
import bean.CompagnieGarantie;
import bean.Energie;
import bean.Garantie;
import bean.Groupe;
import bean.MotoMoteur;
import bean.Police;
import bean.Souscripteur;
import bean.Tarif;
import bean.Telephone;
import bean.Usage;
import bean.VehiculeMoteur;
import bean.Zone;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import static main.Assurances.getController;
import static main.Assurances.getUser;
import view.dialog.CompagnieDialog;
import view.dialog.CompagnieGarantieDialog;
import view.dialog.GarantieDialog;
import view.dialog.PoliceDialog;
import view.dialog.SouscripteurDialog;

/**
 *
 * @author ATH
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        initCB();
        initTable();
        initPop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_souscripteur = new javax.swing.JPopupMenu();
        popup_menu_souscripteur_add = new javax.swing.JMenuItem();
        popup_menu_souscripteur_update = new javax.swing.JMenuItem();
        popup_menu_souscripteur_remove = new javax.swing.JMenuItem();
        buttonGroup = new javax.swing.ButtonGroup();
        popup_compagnie = new javax.swing.JPopupMenu();
        popup_menu_compagnie_add = new javax.swing.JMenuItem();
        popup_menu_compagnie_update = new javax.swing.JMenuItem();
        popup_menu_compagnie_remove = new javax.swing.JMenuItem();
        popup_garantie = new javax.swing.JPopupMenu();
        popup_menu_garantie_add = new javax.swing.JMenuItem();
        popup_menu_garantie_update = new javax.swing.JMenuItem();
        popup_menu_garantie_remove = new javax.swing.JMenuItem();
        popup_compagnie_police = new javax.swing.JPopupMenu();
        popup_menu_compagnie_police_add = new javax.swing.JMenuItem();
        popup_menu_compagnie_police_update = new javax.swing.JMenuItem();
        popup_menu_compagnie_police_remove = new javax.swing.JMenuItem();
        popup_compagnie_garantie = new javax.swing.JPopupMenu();
        popup_menu_compagnie_garantie_add = new javax.swing.JMenuItem();
        popup_menu_compagnie_garantie_update = new javax.swing.JMenuItem();
        popup_menu_compagnie_garantie_remove = new javax.swing.JMenuItem();
        tabbedPane = new javax.swing.JTabbedPane();
        panel_souscripteur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_ajouter_souscripteur = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        scrollPane_souscripteur = new javax.swing.JScrollPane();
        table_souscripteur = new javax.swing.JTable();
        btn_mettre_a_jour_souscripteur = new javax.swing.JButton();
        btn_suprimer_souscripteur = new javax.swing.JButton();
        panel_compagnie_assurance = new javax.swing.JPanel();
        scrollPane_compagnie = new javax.swing.JScrollPane();
        table_compagnie = new javax.swing.JTable();
        panel_compagnie_police = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo_compagnie_usage = new javax.swing.JComboBox<>();
        scrollPane_compagnie_police = new javax.swing.JScrollPane();
        table_compagnie_police = new javax.swing.JTable();
        scrollPane_garantie = new javax.swing.JScrollPane();
        table_garantie = new javax.swing.JTable();
        panel_compagnie_garantie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        combo_compagnie = new javax.swing.JComboBox<>();
        scrollPane_compagnie_garantie = new javax.swing.JScrollPane();
        table_compagnie_garantie = new javax.swing.JTable();
        panel_prime = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combo_prime_usage = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_classe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combo_groupe = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combo_zone = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        combo_puissance = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        combo_energie = new javax.swing.JComboBox<>();
        radio_btn_vehicule = new javax.swing.JRadioButton();
        radio_btn_moto = new javax.swing.JRadioButton();
        scrollPane_prime = new javax.swing.JScrollPane();
        table_prime = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        textField_recherche = new javax.swing.JTextField();

        popup_menu_souscripteur_add.setText("Ajouter souscripteur");
        popup_menu_souscripteur_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_souscripteur_addActionPerformed(evt);
            }
        });
        popup_souscripteur.add(popup_menu_souscripteur_add);

        popup_menu_souscripteur_update.setText("Mettre à jour souscripteur");
        popup_menu_souscripteur_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_souscripteur_updateActionPerformed(evt);
            }
        });
        popup_souscripteur.add(popup_menu_souscripteur_update);

        popup_menu_souscripteur_remove.setText("Suprimer souscripteur");
        popup_menu_souscripteur_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_souscripteur_removeActionPerformed(evt);
            }
        });
        popup_souscripteur.add(popup_menu_souscripteur_remove);

        popup_menu_compagnie_add.setText("Ajouter compagnie");
        popup_menu_compagnie_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_addActionPerformed(evt);
            }
        });
        popup_compagnie.add(popup_menu_compagnie_add);

        popup_menu_compagnie_update.setText("Mettre à jour compagnie");
        popup_menu_compagnie_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_updateActionPerformed(evt);
            }
        });
        popup_compagnie.add(popup_menu_compagnie_update);

        popup_menu_compagnie_remove.setText("Suprimer compagnie");
        popup_menu_compagnie_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_removeActionPerformed(evt);
            }
        });
        popup_compagnie.add(popup_menu_compagnie_remove);

        popup_menu_garantie_add.setText("Ajouter garantie");
        popup_menu_garantie_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_garantie_addActionPerformed(evt);
            }
        });
        popup_garantie.add(popup_menu_garantie_add);

        popup_menu_garantie_update.setText("Mettre à jour garantie");
        popup_menu_garantie_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_garantie_updateActionPerformed(evt);
            }
        });
        popup_garantie.add(popup_menu_garantie_update);

        popup_menu_garantie_remove.setText("Suprimer garantie");
        popup_menu_garantie_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_garantie_removeActionPerformed(evt);
            }
        });
        popup_garantie.add(popup_menu_garantie_remove);

        popup_menu_compagnie_police_add.setText("Ajouter compagnie police");
        popup_menu_compagnie_police_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_police_addActionPerformed(evt);
            }
        });
        popup_compagnie_police.add(popup_menu_compagnie_police_add);

        popup_menu_compagnie_police_update.setText("Mettre à jour compagnie police");
        popup_menu_compagnie_police_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_police_updateActionPerformed(evt);
            }
        });
        popup_compagnie_police.add(popup_menu_compagnie_police_update);

        popup_menu_compagnie_police_remove.setText("Suprimer compagnie police");
        popup_menu_compagnie_police_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_police_removeActionPerformed(evt);
            }
        });
        popup_compagnie_police.add(popup_menu_compagnie_police_remove);

        popup_menu_compagnie_garantie_add.setText("Ajouter compagnie garantie");
        popup_menu_compagnie_garantie_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_garantie_addActionPerformed(evt);
            }
        });
        popup_compagnie_garantie.add(popup_menu_compagnie_garantie_add);

        popup_menu_compagnie_garantie_update.setText("Mettre à jour compagnie garantie");
        popup_menu_compagnie_garantie_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_garantie_updateActionPerformed(evt);
            }
        });
        popup_compagnie_garantie.add(popup_menu_compagnie_garantie_update);

        popup_menu_compagnie_garantie_remove.setText("Suprimer compagnie garantie");
        popup_menu_compagnie_garantie_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menu_compagnie_garantie_removeActionPerformed(evt);
            }
        });
        popup_compagnie_garantie.add(popup_menu_compagnie_garantie_remove);

        jLabel1.setText("Rechercher");

        btn_ajouter_souscripteur.setText("Ajouter souscripteur");
        btn_ajouter_souscripteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter_souscripteurActionPerformed(evt);
            }
        });

        table_souscripteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Numéro assuré", "Nom et Prénom", "Type pièce", "Numéro pièce", "Téléphone", "Adresse", "Profession", "Personalité", "Exempter taxe", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_souscripteur.setViewportView(table_souscripteur);
        if (table_souscripteur.getColumnModel().getColumnCount() > 0) {
            table_souscripteur.getColumnModel().getColumn(0).setMinWidth(35);
            table_souscripteur.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_souscripteur.getColumnModel().getColumn(0).setMaxWidth(35);
            table_souscripteur.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(2).setPreferredWidth(300);
            table_souscripteur.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(5).setPreferredWidth(150);
            table_souscripteur.getColumnModel().getColumn(6).setPreferredWidth(200);
            table_souscripteur.getColumnModel().getColumn(7).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(8).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(9).setPreferredWidth(100);
            table_souscripteur.getColumnModel().getColumn(10).setMinWidth(5);
            table_souscripteur.getColumnModel().getColumn(10).setPreferredWidth(5);
            table_souscripteur.getColumnModel().getColumn(10).setMaxWidth(5);
        }

        btn_mettre_a_jour_souscripteur.setText("Modifier souscripteur");
        btn_mettre_a_jour_souscripteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mettre_a_jour_souscripteurActionPerformed(evt);
            }
        });

        btn_suprimer_souscripteur.setText("Suprimer souscripteur");
        btn_suprimer_souscripteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suprimer_souscripteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_souscripteurLayout = new javax.swing.GroupLayout(panel_souscripteur);
        panel_souscripteur.setLayout(panel_souscripteurLayout);
        panel_souscripteurLayout.setHorizontalGroup(
            panel_souscripteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_souscripteurLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ajouter_souscripteur)
                .addGap(18, 18, 18)
                .addComponent(btn_mettre_a_jour_souscripteur)
                .addGap(18, 18, 18)
                .addComponent(btn_suprimer_souscripteur)
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(scrollPane_souscripteur, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel_souscripteurLayout.setVerticalGroup(
            panel_souscripteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_souscripteurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_souscripteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panel_souscripteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ajouter_souscripteur)
                        .addComponent(btn_mettre_a_jour_souscripteur)
                        .addComponent(btn_suprimer_souscripteur)))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_souscripteur, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Souscripteur", panel_souscripteur);

        scrollPane_compagnie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Table des compagnies d'assurance"));

        table_compagnie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "N°", "Compagnie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_compagnie.setViewportView(table_compagnie);
        if (table_compagnie.getColumnModel().getColumnCount() > 0) {
            table_compagnie.getColumnModel().getColumn(0).setMinWidth(35);
            table_compagnie.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_compagnie.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        panel_compagnie_police.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Table compagnies N°Police"));

        jLabel2.setText("Usage Auto");

        combo_compagnie_usage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table_compagnie_police.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Usage", "Compagnie", "Police", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_compagnie_police.setViewportView(table_compagnie_police);
        if (table_compagnie_police.getColumnModel().getColumnCount() > 0) {
            table_compagnie_police.getColumnModel().getColumn(0).setMinWidth(35);
            table_compagnie_police.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_compagnie_police.getColumnModel().getColumn(0).setMaxWidth(35);
            table_compagnie_police.getColumnModel().getColumn(3).setMinWidth(100);
            table_compagnie_police.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_compagnie_police.getColumnModel().getColumn(3).setMaxWidth(100);
            table_compagnie_police.getColumnModel().getColumn(4).setMinWidth(5);
            table_compagnie_police.getColumnModel().getColumn(4).setPreferredWidth(5);
            table_compagnie_police.getColumnModel().getColumn(4).setMaxWidth(5);
        }

        javax.swing.GroupLayout panel_compagnie_policeLayout = new javax.swing.GroupLayout(panel_compagnie_police);
        panel_compagnie_police.setLayout(panel_compagnie_policeLayout);
        panel_compagnie_policeLayout.setHorizontalGroup(
            panel_compagnie_policeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_policeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_policeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane_compagnie_police, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(panel_compagnie_policeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(combo_compagnie_usage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_compagnie_policeLayout.setVerticalGroup(
            panel_compagnie_policeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_policeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_policeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_compagnie_usage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_compagnie_police, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrollPane_garantie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Table des garanties"));

        table_garantie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "N°", "Garantie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_garantie.setViewportView(table_garantie);
        if (table_garantie.getColumnModel().getColumnCount() > 0) {
            table_garantie.getColumnModel().getColumn(0).setMinWidth(35);
            table_garantie.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_garantie.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        panel_compagnie_garantie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Table compagnies garanties"));

        jLabel3.setText("Compagnie");

        combo_compagnie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table_compagnie_garantie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Compagnie", "Garantie", "Montant", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_compagnie_garantie.setViewportView(table_compagnie_garantie);
        if (table_compagnie_garantie.getColumnModel().getColumnCount() > 0) {
            table_compagnie_garantie.getColumnModel().getColumn(0).setMinWidth(35);
            table_compagnie_garantie.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_compagnie_garantie.getColumnModel().getColumn(0).setMaxWidth(35);
            table_compagnie_garantie.getColumnModel().getColumn(3).setMinWidth(100);
            table_compagnie_garantie.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_compagnie_garantie.getColumnModel().getColumn(3).setMaxWidth(100);
            table_compagnie_garantie.getColumnModel().getColumn(4).setMinWidth(5);
            table_compagnie_garantie.getColumnModel().getColumn(4).setPreferredWidth(5);
            table_compagnie_garantie.getColumnModel().getColumn(4).setMaxWidth(5);
        }

        javax.swing.GroupLayout panel_compagnie_garantieLayout = new javax.swing.GroupLayout(panel_compagnie_garantie);
        panel_compagnie_garantie.setLayout(panel_compagnie_garantieLayout);
        panel_compagnie_garantieLayout.setHorizontalGroup(
            panel_compagnie_garantieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_garantieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_garantieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane_compagnie_garantie)
                    .addGroup(panel_compagnie_garantieLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(combo_compagnie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_compagnie_garantieLayout.setVerticalGroup(
            panel_compagnie_garantieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_garantieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_garantieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_compagnie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_compagnie_garantie, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_compagnie_assuranceLayout = new javax.swing.GroupLayout(panel_compagnie_assurance);
        panel_compagnie_assurance.setLayout(panel_compagnie_assuranceLayout);
        panel_compagnie_assuranceLayout.setHorizontalGroup(
            panel_compagnie_assuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_assuranceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_assuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_compagnie_assuranceLayout.createSequentialGroup()
                        .addComponent(scrollPane_compagnie, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_compagnie_police, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_compagnie_assuranceLayout.createSequentialGroup()
                        .addComponent(scrollPane_garantie, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_compagnie_garantie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_compagnie_assuranceLayout.setVerticalGroup(
            panel_compagnie_assuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compagnie_assuranceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compagnie_assuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane_compagnie, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel_compagnie_police, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_compagnie_assuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane_garantie, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel_compagnie_garantie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Compagnie assurance", panel_compagnie_assurance);

        jLabel4.setText("Usage");

        combo_prime_usage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_prime_usageActionPerformed(evt);
            }
        });

        jLabel5.setText("Classe");

        combo_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_classeActionPerformed(evt);
            }
        });

        jLabel6.setText("Groupe");

        combo_groupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_groupeActionPerformed(evt);
            }
        });

        jLabel7.setText("Zone");

        combo_zone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_zoneActionPerformed(evt);
            }
        });

        jLabel8.setText("Puissance");

        combo_puissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_puissanceActionPerformed(evt);
            }
        });

        jLabel9.setText("Energie");

        combo_energie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_energieActionPerformed(evt);
            }
        });

        buttonGroup.add(radio_btn_vehicule);
        radio_btn_vehicule.setSelected(true);
        radio_btn_vehicule.setText("Véhicule");
        radio_btn_vehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_vehiculeActionPerformed(evt);
            }
        });

        buttonGroup.add(radio_btn_moto);
        radio_btn_moto.setText("Moto");
        radio_btn_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_motoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(combo_prime_usage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(combo_classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(combo_groupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(combo_zone, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(combo_puissance, 0, 148, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(combo_energie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_btn_vehicule)
                        .addGap(18, 18, 18)
                        .addComponent(radio_btn_moto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_btn_vehicule)
                    .addComponent(radio_btn_moto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_prime_usage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(combo_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(combo_groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(combo_zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(combo_energie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(combo_puissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_prime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Usage", "Classe", "Groupe", "Zone", "Puissance", "Energie", "Tarif", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_prime.setViewportView(table_prime);
        if (table_prime.getColumnModel().getColumnCount() > 0) {
            table_prime.getColumnModel().getColumn(0).setMinWidth(35);
            table_prime.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_prime.getColumnModel().getColumn(0).setMaxWidth(35);
            table_prime.getColumnModel().getColumn(1).setPreferredWidth(250);
            table_prime.getColumnModel().getColumn(5).setPreferredWidth(200);
            table_prime.getColumnModel().getColumn(8).setMinWidth(5);
            table_prime.getColumnModel().getColumn(8).setPreferredWidth(5);
            table_prime.getColumnModel().getColumn(8).setMaxWidth(5);
        }

        jLabel10.setText("Rechercher");

        javax.swing.GroupLayout panel_primeLayout = new javax.swing.GroupLayout(panel_prime);
        panel_prime.setLayout(panel_primeLayout);
        panel_primeLayout.setHorizontalGroup(
            panel_primeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_primeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_primeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane_prime, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(panel_primeLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(textField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_primeLayout.setVerticalGroup(
            panel_primeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_primeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_primeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_primeLayout.createSequentialGroup()
                        .addGroup(panel_primeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollPane_prime, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Prime", panel_prime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajouter_souscripteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter_souscripteurActionPerformed
        ajout_souscripteur();
    }//GEN-LAST:event_btn_ajouter_souscripteurActionPerformed

    private void popup_menu_souscripteur_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_souscripteur_addActionPerformed
        ajout_souscripteur();
    }//GEN-LAST:event_popup_menu_souscripteur_addActionPerformed

    private void popup_menu_souscripteur_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_souscripteur_updateActionPerformed
        mettre_a_jour_souscripteur(table_souscripteur.getSelectedRow());
    }//GEN-LAST:event_popup_menu_souscripteur_updateActionPerformed

    private void popup_menu_souscripteur_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_souscripteur_removeActionPerformed
        suprimer_souscripteur(table_souscripteur.getSelectedRow());
    }//GEN-LAST:event_popup_menu_souscripteur_removeActionPerformed

    private void btn_mettre_a_jour_souscripteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mettre_a_jour_souscripteurActionPerformed
        mettre_a_jour_souscripteur(table_souscripteur.getSelectedRow());
    }//GEN-LAST:event_btn_mettre_a_jour_souscripteurActionPerformed

    private void btn_suprimer_souscripteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suprimer_souscripteurActionPerformed
        suprimer_souscripteur(table_souscripteur.getSelectedRow());
    }//GEN-LAST:event_btn_suprimer_souscripteurActionPerformed

    private void combo_energieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_energieActionPerformed
        initCBPuissance();
        updateTablePrime();
    }//GEN-LAST:event_combo_energieActionPerformed

    private void radio_btn_vehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_vehiculeActionPerformed
        initCBPuissance();
        combo_energie.setEnabled(true);
        updateTablePrime();
    }//GEN-LAST:event_radio_btn_vehiculeActionPerformed

    private void radio_btn_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_motoActionPerformed
        initCBPuissance();
        combo_energie.setEnabled(false);
        updateTablePrime();
    }//GEN-LAST:event_radio_btn_motoActionPerformed

    private void combo_prime_usageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_prime_usageActionPerformed
        updateTablePrime();
    }//GEN-LAST:event_combo_prime_usageActionPerformed

    private void combo_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_classeActionPerformed
        updateTablePrime();
    }//GEN-LAST:event_combo_classeActionPerformed

    private void combo_groupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_groupeActionPerformed
        updateTablePrime();
    }//GEN-LAST:event_combo_groupeActionPerformed

    private void combo_zoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_zoneActionPerformed
        updateTablePrime();
    }//GEN-LAST:event_combo_zoneActionPerformed

    private void combo_puissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_puissanceActionPerformed
        updateTablePrime();
    }//GEN-LAST:event_combo_puissanceActionPerformed

    private void popup_menu_compagnie_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_addActionPerformed
        ajout_compagnie();
    }//GEN-LAST:event_popup_menu_compagnie_addActionPerformed

    private void popup_menu_compagnie_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_updateActionPerformed
        mettre_a_jour_compagnie(table_compagnie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_updateActionPerformed

    private void popup_menu_compagnie_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_removeActionPerformed
        suprimer_compagnie(table_compagnie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_removeActionPerformed

    private void popup_menu_garantie_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_garantie_addActionPerformed
        ajout_garantie();
    }//GEN-LAST:event_popup_menu_garantie_addActionPerformed

    private void popup_menu_garantie_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_garantie_updateActionPerformed
        mettre_a_jour_garantie(table_garantie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_garantie_updateActionPerformed

    private void popup_menu_garantie_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_garantie_removeActionPerformed
        suprimer_garantie(table_garantie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_garantie_removeActionPerformed

    private void popup_menu_compagnie_police_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_police_addActionPerformed
        ajout_police();
    }//GEN-LAST:event_popup_menu_compagnie_police_addActionPerformed

    private void popup_menu_compagnie_police_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_police_updateActionPerformed
        mettre_a_jour_police(table_compagnie_police.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_police_updateActionPerformed

    private void popup_menu_compagnie_police_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_police_removeActionPerformed
        suprimer_police(table_compagnie_police.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_police_removeActionPerformed

    private void popup_menu_compagnie_garantie_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_garantie_addActionPerformed
        ajout_compagnie_garantie();
    }//GEN-LAST:event_popup_menu_compagnie_garantie_addActionPerformed

    private void popup_menu_compagnie_garantie_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_garantie_updateActionPerformed
        mettre_a_jour_compagnie_garantie(table_compagnie_garantie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_garantie_updateActionPerformed

    private void popup_menu_compagnie_garantie_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menu_compagnie_garantie_removeActionPerformed
        suprimer_compagnie_garantie(table_compagnie_garantie.getSelectedRow());
    }//GEN-LAST:event_popup_menu_compagnie_garantie_removeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter_souscripteur;
    private javax.swing.JButton btn_mettre_a_jour_souscripteur;
    private javax.swing.JButton btn_suprimer_souscripteur;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> combo_classe;
    private javax.swing.JComboBox<String> combo_compagnie;
    private javax.swing.JComboBox<String> combo_compagnie_usage;
    private javax.swing.JComboBox<String> combo_energie;
    private javax.swing.JComboBox<String> combo_groupe;
    private javax.swing.JComboBox<String> combo_prime_usage;
    private javax.swing.JComboBox<String> combo_puissance;
    private javax.swing.JComboBox<String> combo_zone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel_compagnie_assurance;
    private javax.swing.JPanel panel_compagnie_garantie;
    private javax.swing.JPanel panel_compagnie_police;
    private javax.swing.JPanel panel_prime;
    private javax.swing.JPanel panel_souscripteur;
    private javax.swing.JPopupMenu popup_compagnie;
    private javax.swing.JPopupMenu popup_compagnie_garantie;
    private javax.swing.JPopupMenu popup_compagnie_police;
    private javax.swing.JPopupMenu popup_garantie;
    private javax.swing.JMenuItem popup_menu_compagnie_add;
    private javax.swing.JMenuItem popup_menu_compagnie_garantie_add;
    private javax.swing.JMenuItem popup_menu_compagnie_garantie_remove;
    private javax.swing.JMenuItem popup_menu_compagnie_garantie_update;
    private javax.swing.JMenuItem popup_menu_compagnie_police_add;
    private javax.swing.JMenuItem popup_menu_compagnie_police_remove;
    private javax.swing.JMenuItem popup_menu_compagnie_police_update;
    private javax.swing.JMenuItem popup_menu_compagnie_remove;
    private javax.swing.JMenuItem popup_menu_compagnie_update;
    private javax.swing.JMenuItem popup_menu_garantie_add;
    private javax.swing.JMenuItem popup_menu_garantie_remove;
    private javax.swing.JMenuItem popup_menu_garantie_update;
    private javax.swing.JMenuItem popup_menu_souscripteur_add;
    private javax.swing.JMenuItem popup_menu_souscripteur_remove;
    private javax.swing.JMenuItem popup_menu_souscripteur_update;
    private javax.swing.JPopupMenu popup_souscripteur;
    private javax.swing.JRadioButton radio_btn_moto;
    private javax.swing.JRadioButton radio_btn_vehicule;
    private javax.swing.JScrollPane scrollPane_compagnie;
    private javax.swing.JScrollPane scrollPane_compagnie_garantie;
    private javax.swing.JScrollPane scrollPane_compagnie_police;
    private javax.swing.JScrollPane scrollPane_garantie;
    private javax.swing.JScrollPane scrollPane_prime;
    private javax.swing.JScrollPane scrollPane_souscripteur;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable table_compagnie;
    private javax.swing.JTable table_compagnie_garantie;
    private javax.swing.JTable table_compagnie_police;
    private javax.swing.JTable table_garantie;
    private javax.swing.JTable table_prime;
    private javax.swing.JTable table_souscripteur;
    private javax.swing.JTextField textField_recherche;
    // End of variables declaration//GEN-END:variables

    private static void addPopup(Component component, final JPopupMenu popup) {
        component.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showMenu(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showMenu(e);
                }
            }

            private void showMenu(MouseEvent e) {
                popup.show(e.getComponent(), e.getX(), e.getY());
            }
        });
    }

    private void initPop() {
        addPopup(table_souscripteur, popup_souscripteur);
        addPopup(scrollPane_souscripteur, popup_souscripteur);

        addPopup(table_compagnie, popup_compagnie);
        addPopup(scrollPane_compagnie, popup_compagnie);

        addPopup(table_garantie, popup_garantie);
        addPopup(scrollPane_garantie, popup_garantie);

        addPopup(table_compagnie_police, popup_compagnie_police);
        addPopup(scrollPane_compagnie_police, popup_compagnie_police);

        addPopup(table_compagnie_garantie, popup_compagnie_garantie);
        addPopup(scrollPane_compagnie_garantie, popup_compagnie_garantie);
    }

    private void initTable() {
        updateTableSouscripteur();
        updateTableCompagnie();
        updateTableGarantie();
        updateTableCompagnieGarantie();
        updateTableCompagniePolice();
        updateTablePrime();
    }

    private void updateTableSouscripteur() {
        DefaultTableModel model = (DefaultTableModel) table_souscripteur.getModel();
        model.setRowCount(0);
        ArrayList<Souscripteur> list = getController().getSouscripteurController().getSouscripteurs();
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[11];
            colonne[0] = i + 1;
            colonne[1] = list.get(i).getNumero_assure();
            colonne[2] = list.get(i).getNom_prenom();
            colonne[3] = list.get(i).getType_piece();
            colonne[4] = list.get(i).getNumero_piece();
            ArrayList<Telephone> telephones = getController().getTelephoneController().getTelephones(list.get(i).getId());
            String tel = "";
            if (telephones.size() > 2) {
                for (int j = 0; j < telephones.size() - 1; j++) {
                    tel += telephones.get(j).getTelephone() + " / ";
                }
                tel += telephones.get(telephones.size() - 1).getTelephone();
            } else if (telephones.size() == 2) {
                tel = telephones.get(0).getTelephone() + " / " + telephones.get(1).getTelephone();
            } else if (telephones.size() == 1) {
                tel = telephones.get(0).getTelephone();
            }

            tel = tel.substring(0, tel.length());
            colonne[5] = tel;
            colonne[6] = list.get(i).getAdresse();
            colonne[7] = list.get(i).getProfession();
            colonne[8] = list.get(i).getPersonnalite();
            colonne[9] = list.get(i).isExempter_taxe();
            colonne[10] = list.get(i).getId();
            model.addRow(colonne);
        }
        table_souscripteur.setModel(model);
    }

    private void updateTableCompagnie() {
        DefaultTableModel model = (DefaultTableModel) table_compagnie.getModel();
        model.setRowCount(0);
        ArrayList<Compagnie> list = getController().getCompagnieController().getCompagnies();
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[2];
            colonne[0] = i + 1;
            colonne[1] = list.get(i).getCompagnie();
            model.addRow(colonne);
        }
        table_compagnie.setModel(model);
    }

    private void updateTableGarantie() {
        DefaultTableModel model = (DefaultTableModel) table_garantie.getModel();
        model.setRowCount(0);
        ArrayList<Garantie> list = getController().getGarantieController().getGaranties();
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[2];
            colonne[0] = i + 1;
            colonne[1] = list.get(i).getGarantie();
            model.addRow(colonne);
        }
        table_garantie.setModel(model);
    }

    private void updateTableCompagnieGarantie() {
        DefaultTableModel model = (DefaultTableModel) table_compagnie_garantie.getModel();
        model.setRowCount(0);
        ArrayList<CompagnieGarantie> list = getController().getCompagnieGarantieController().getCompagnieGaranties();
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[5];
            colonne[0] = i + 1;
            colonne[1] = getController().getCompagnieController().getCompagnie(list.get(i).getId_compagnie()).getCompagnie();
            colonne[2] = getController().getGarantieController().getGarantie(list.get(i).getId_garantie()).getGarantie();
            colonne[3] = list.get(i).getMontant();
            colonne[4] = list.get(i).getId();
            model.addRow(colonne);
        }
        table_compagnie_garantie.setModel(model);
    }

    private void updateTableCompagniePolice() {
        DefaultTableModel model = (DefaultTableModel) table_compagnie_police.getModel();
        model.setRowCount(0);
        ArrayList<Police> list = getController().getPoliceController().getPolices();
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[5];
            colonne[0] = i + 1;
            colonne[1] = getController().getUsageController().getUsage(list.get(i).getId_usage()).getUsage();
            colonne[2] = getController().getCompagnieController().getCompagnie(list.get(i).getId_compagnie()).getCompagnie();
            colonne[3] = list.get(i).getPolice();
            colonne[4] = list.get(i).getId();
            model.addRow(colonne);
        }
        table_compagnie_police.setModel(model);
    }

    private void ajout_souscripteur() {
        if (!getController().getDroitController().getDroit(getUser().getId()).isEcriture()) {
            droit_ajout();
            return;
        }
        SouscripteurDialog souscripteurDialog = new SouscripteurDialog(null, true);
        souscripteurDialog.setVisible(true);
        updateTableSouscripteur();
    }

    private void ajout_compagnie() {
        if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
            droit_administration();
            return;
        }
        CompagnieDialog compagnieDialog = new CompagnieDialog(null, true);
        compagnieDialog.setVisible(true);
        updateTableCompagnie();
        initCBCompagnie();
    }

    private void suprimer_compagnie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            String nom_compagnie = table_compagnie.getValueAt(row, table_compagnie.getColumnCount() - 1).toString();
            Compagnie compagnie = getController().getCompagnieController().getCompagnie(nom_compagnie);
            int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer la compagnie " + compagnie.getCompagnie() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                getController().getCompagnieController().removeCompagnie(compagnie.getId());
                updateTableCompagnie();
                initCBCompagnie();
            }
        }
    }

    private void mettre_a_jour_compagnie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            String compagnie = table_compagnie.getValueAt(row, table_compagnie.getColumnCount() - 1).toString();
            CompagnieDialog compagnieDialog = new CompagnieDialog(null, true, getController().getCompagnieController().getCompagnie(compagnie));
            compagnieDialog.setVisible(true);
            updateTableCompagnie();
            initCBCompagnie();
        }

    }

    private void ajout_garantie() {
        if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
            droit_administration();
            return;
        }
        GarantieDialog garantieDialog = new GarantieDialog(null, true);
        garantieDialog.setVisible(true);
        updateTableGarantie();
    }

    private void mettre_a_jour_garantie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            String garantie = table_garantie.getValueAt(row, table_garantie.getColumnCount() - 1).toString();
            GarantieDialog garantieDialog = new GarantieDialog(null, true, getController().getGarantieController().getGarantie(garantie));
            garantieDialog.setVisible(true);
            updateTableGarantie();
        }

    }

    private void suprimer_garantie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            String nom_garantie = table_garantie.getValueAt(row, table_garantie.getColumnCount() - 1).toString();
            Garantie garantie = getController().getGarantieController().getGarantie(nom_garantie);
            int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer la garantie " + garantie.getGarantie() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                getController().getGarantieController().removeGarantie(garantie.getId());
                updateTableGarantie();
            }
        }
    }

    private void ajout_police() {
        if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
            droit_administration();
            return;
        }
        PoliceDialog policeDialog = new PoliceDialog(null, true);
        policeDialog.setVisible(true);
        updateTableCompagniePolice();
    }

    private void mettre_a_jour_police(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            long id_police = Long.parseLong(table_compagnie_police.getValueAt(row, table_compagnie_police.getColumnCount() - 1).toString());
            PoliceDialog policeDialog = new PoliceDialog(null, true, getController().getPoliceController().getPolice(id_police));
            policeDialog.setVisible(true);
            updateTableCompagniePolice();
        }

    }

    private void suprimer_police(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            long id_police = Long.parseLong(table_compagnie_police.getValueAt(row, table_compagnie_police.getColumnCount() - 1).toString());
            Police police = getController().getPoliceController().getPolice(id_police);
            int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer le numéro de police " + police.getPolice() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                getController().getPoliceController().removePolice(police.getId());
                updateTableGarantie();
            }
        }
    }

    private void ajout_compagnie_garantie() {
        if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
            droit_administration();
            return;
        }
        CompagnieGarantieDialog compagnieGarantieDialog = new CompagnieGarantieDialog(null, true);
        compagnieGarantieDialog.setVisible(true);
        updateTableCompagnieGarantie();
    }

    private void mettre_a_jour_compagnie_garantie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            long id_compagnie_garantie = Long.parseLong(table_compagnie_garantie.getValueAt(row, table_compagnie_garantie.getColumnCount() - 1).toString());
            CompagnieGarantieDialog compagnieGarantieDialog = new CompagnieGarantieDialog(null, true, getController().getCompagnieGarantieController().getCompagnieGarantie(id_compagnie_garantie));
            compagnieGarantieDialog.setVisible(true);
            updateTableCompagnieGarantie();
        }

    }

    private void suprimer_compagnie_garantie(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isAdministration()) {
                droit_administration();
                return;
            }
            long id_compagnie_garantie = Long.parseLong(table_compagnie_garantie.getValueAt(row, table_compagnie_garantie.getColumnCount() - 1).toString());
            CompagnieGarantie compagnieGarantie = getController().getCompagnieGarantieController().getCompagnieGarantie(id_compagnie_garantie);
            int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer le montant " + compagnieGarantie.getMontant() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                getController().getCompagnieGarantieController().removeCompagnieGarantie(compagnieGarantie.getId());
                updateTableCompagnieGarantie();
            }
        }
    }

    private void updateTablePrime() {
        DefaultTableModel model = (DefaultTableModel) table_prime.getModel();
        model.setRowCount(0);
        if (combo_classe.getSelectedIndex() < 0 || combo_prime_usage.getSelectedIndex() < 0 || combo_groupe.getSelectedIndex() < 0 || combo_zone.getSelectedIndex() < 0 || combo_puissance.getSelectedIndex() < 0 || combo_energie.getSelectedIndex() < 0) {
            return;
        }
        long id_usage = 0, id_classe = 0, id_groupe = 0, id_zone = 0, id_energie = 0, id_puissance = 0;
        Usage usage = getController().getUsageController().getUsage(combo_prime_usage.getSelectedItem().toString());
        if (usage != null) {
            id_usage = usage.getId();
        }
        Classe classe;
        try {
            classe = getController().getClasseController().getClasse(Long.parseLong(combo_classe.getSelectedItem().toString()));
        } catch (NumberFormatException e) {
            classe = null;
        }
        if (classe != null) {
            id_classe = classe.getId();
        }
        Groupe groupe;
        try {
            groupe = getController().getGroupeController().getGroupe(Long.parseLong(combo_groupe.getSelectedItem().toString()));
        } catch (NumberFormatException e) {
            groupe = null;
        }
        if (groupe != null) {
            id_groupe = groupe.getId();
        }
        Zone zone = getController().getZoneController().getZone(combo_zone.getSelectedItem().toString());
        if (zone != null) {
            id_zone = zone.getId();
        }
        Energie energie = getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString());
        if (energie != null) {
            id_energie = energie.getId();
        }
        int type = 0;
        if (radio_btn_vehicule.isSelected()) {
            type = 1;
            VehiculeMoteur vehiculeMoteur = getController().getVehiculeMoteurController().getVehiculeMoteur(combo_puissance.getSelectedItem().toString());
            if (vehiculeMoteur != null) {
                id_puissance = vehiculeMoteur.getId();
            }
        }
        if (radio_btn_moto.isSelected()) {
            type = 2;
            MotoMoteur motoMoteur = getController().getMotoMoteurController().getMotoMoteur(combo_puissance.getSelectedItem().toString());
            if (motoMoteur != null) {
                id_puissance = motoMoteur.getId();
            }
        }
        ArrayList<Tarif> list = getController().getTarifController().getTarifs(id_classe, id_groupe, id_zone, id_usage, id_puissance, id_energie, type);
        for (int i = 0; i < list.size(); i++) {
            Object colonne[] = new Object[9];
            colonne[0] = i + 1;
            colonne[1] = getController().getUsageController().getUsage(list.get(i).getId_usage()).getUsage();
            colonne[2] = getController().getClasseController().getClasse(list.get(i).getId_classe()).getId();
            colonne[3] = getController().getGroupeController().getGroupe(list.get(i).getId_groupe()).getId();
            colonne[4] = getController().getZoneController().getZone(list.get(i).getId_zone()).getZone();
            if (getController().getTarifController().getVehiculeController().getVehicule(list.get(i).getId()) != null) {
                colonne[5] = getController().getVehiculeMoteurController().getVehiculeMoteur(getController().getTarifController().getVehiculeController().getVehicule(list.get(i).getId()).getId_puissance()).getPuissance();
                colonne[6] = getController().getEnergieController().getEnergie(getController().getVehiculeMoteurController().getVehiculeMoteur(getController().getTarifController().getVehiculeController().getVehicule(list.get(i).getId()).getId_puissance()).getId_energie()).getEnergie();
            } else {
                colonne[5] = getController().getMotoMoteurController().getMotoMoteur(getController().getTarifController().getMotoController().getMoto(list.get(i).getId()).getId_puissance()).getPuissance();
                colonne[6] = "";
            }
            colonne[7] = list.get(i).getTarif();
            colonne[8] = list.get(i).getId();
            model.addRow(colonne);
        }
        table_prime.setModel(model);
    }

    private void mettre_a_jour_souscripteur(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isModification()) {
                droit_modification();
                return;
            }
            Souscripteur souscripteur = getController().getSouscripteurController().getSouscripteur(Long.parseLong(table_souscripteur.getValueAt(row, table_souscripteur.getColumnCount() - 1).toString()));
            SouscripteurDialog souscripteurDialog = new SouscripteurDialog(null, true, souscripteur);
            souscripteurDialog.setVisible(true);
            updateTableSouscripteur();
        }
    }

    private void suprimer_souscripteur(int row) {
        if (row > -1) {
            if (!getController().getDroitController().getDroit(getUser().getId()).isSupression()) {
                droit_supression();
                return;
            }
            Souscripteur souscripteur = getController().getSouscripteurController().getSouscripteur(Long.parseLong(table_souscripteur.getValueAt(row, table_souscripteur.getColumnCount() - 1).toString()));
            int choice = JOptionPane.showConfirmDialog(this, "Etes vous sure de vouloir suprimer le souscripteur " + souscripteur.getNom_prenom() + " ?", "Action irréversible", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                getController().getSouscripteurController().removeSouscripteur(souscripteur.getId());
                updateTableSouscripteur();
            }
        }
    }

    private void initCBPrimeUsage() {
        combo_prime_usage.removeAllItems();
        combo_prime_usage.addItem("Tous");
        getController().getUsageController().getUsages().forEach((u) -> {
            combo_prime_usage.addItem(u.getUsage());
        });
    }

    private void initCBCompagnieUsage() {
        combo_compagnie_usage.removeAllItems();
        combo_compagnie_usage.addItem("Tous");
        getController().getUsageController().getUsages().forEach((u) -> {
            combo_compagnie_usage.addItem(u.getUsage());
        });
    }

    private void initCBClasse() {
        combo_classe.removeAllItems();
        combo_classe.addItem("Toutes");
        getController().getClasseController().getClasses().forEach((c) -> {
            combo_classe.addItem("" + c.getId());
        });
    }

    private void initCBGroupe() {
        combo_groupe.removeAllItems();
        combo_groupe.addItem("Tous");
        getController().getGroupeController().getGroupes().forEach((g) -> {
            combo_groupe.addItem("" + g.getId());
        });
    }

    private void initCBZone() {
        combo_zone.removeAllItems();
        combo_zone.addItem("Toutes");
        getController().getZoneController().getZones().forEach((z) -> {
            combo_zone.addItem(z.getZone());
        });
    }

    private void initCBEnergie() {
        combo_energie.removeAllItems();
        combo_energie.addItem("Toutes");
        getController().getEnergieController().getEnergies().forEach((e) -> {
            combo_energie.addItem(e.getEnergie());
        });
    }

    private void initCBCompagnie() {
        combo_compagnie.removeAllItems();
        getController().getCompagnieController().getCompagnies().forEach((c) -> {
            combo_compagnie.addItem(c.getCompagnie());
        });
    }

    private void initCBPuissance() {
        combo_puissance.removeAllItems();
        combo_puissance.addItem("Toutes");
        if (radio_btn_vehicule.isSelected()) {
            long id_energie = 0;
            if (combo_energie.getSelectedIndex() > -1) {
                if (getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString()) != null) {
                    id_energie = getController().getEnergieController().getEnergie(combo_energie.getSelectedItem().toString()).getId();
                }
            }

            getController().getVehiculeMoteurController().getVehiculeMoteurs(id_energie).forEach((p) -> {
                combo_puissance.addItem(p.getPuissance());
            });
        }
        if (radio_btn_moto.isSelected()) {
            getController().getMotoMoteurController().getMotoMoteurs().forEach((p) -> {
                combo_puissance.addItem(p.getPuissance());
            });
        }
    }

    private void initCB() {
        initCBPrimeUsage();
        initCBCompagnieUsage();
        initCBClasse();
        initCBGroupe();
        initCBZone();
        initCBEnergie();
        initCBPuissance();
        initCBCompagnie();
    }

    private void droit_ajout() {
        JOptionPane.showMessageDialog(this, "Droit d'ajout est réquiert pour effectuer cette opération. ", "Droit d'ajout !", JOptionPane.INFORMATION_MESSAGE);
    }

    private void droit_modification() {
        JOptionPane.showMessageDialog(this, "Droit de modification est réquiert pour effectuer cette opération. ", "Droit de modification !", JOptionPane.INFORMATION_MESSAGE);
    }

    private void droit_supression() {
        JOptionPane.showMessageDialog(this, "Droit de supression est réquiert pour effectuer cette opération. ", "Droit de supression !", JOptionPane.INFORMATION_MESSAGE);
    }

    private void droit_administration() {
        JOptionPane.showMessageDialog(this, "Droit d'administration est réquiert pour effectuer cette opération. ", "Droit d'administration !", JOptionPane.INFORMATION_MESSAGE);
    }
}
