/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.frame;

import java.awt.EventQueue;
import view.dialog.AdresseDialog;
import view.panel.ConfigurationPanel;
import view.panel.MainPanel;

/**
 *
 * @author ATH
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_item_mono = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_item_db = new javax.swing.JMenuItem();
        menu_item_saisie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 700));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        menu_item_mono.setText("Mono");
        menu_item_mono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_monoActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_mono);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configuration");

        menu_item_db.setText("Base de données");
        menu_item_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_dbActionPerformed(evt);
            }
        });
        jMenu3.add(menu_item_db);

        menu_item_saisie.setText("Saisie");
        menu_item_saisie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_saisieActionPerformed(evt);
            }
        });
        jMenu3.add(menu_item_saisie);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_saisieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_saisieActionPerformed
        setContentPane(new ConfigurationPanel());
        revalidate();
        repaint();
    }//GEN-LAST:event_menu_item_saisieActionPerformed

    private void menu_item_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_dbActionPerformed
        AdresseDialog adresseDialog = new AdresseDialog(this, true);
        adresseDialog.setVisible(true);
    }//GEN-LAST:event_menu_item_dbActionPerformed

    private void menu_item_monoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_monoActionPerformed
        setContentPane(new MainPanel());
        revalidate();
        repaint();
    }//GEN-LAST:event_menu_item_monoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        EventQueue.invokeLater(() -> {
            try {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
            } catch (Exception e) {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_item_db;
    private javax.swing.JMenuItem menu_item_mono;
    private javax.swing.JMenuItem menu_item_saisie;
    // End of variables declaration//GEN-END:variables
}
